version: "3.7"
services:
  app:
    image: mnist_edge
    environment:
      OPERATOR_URI: operator:8787
    volumes:
      - type: volume
        source: shared
        target: /repos
  operator:
    image: harmonia/operator
    ports:
      - '9080:9080'
    volumes:
      - ./config.yml:/app/config.yml
      - type: volume
        source: shared
        target: /repos
volumes:
  shared:
